### PR TITLE
fix: shouldUseRouter() always return true

### LINKED ISSUE #42: shouldUseRouter() always return true
In source code we can find
```
const DEFAULT_USE_ROUTER = true
```
and
```
function shouldUseRouter(moduleOptions, $config) {
  return moduleOptionRouter(moduleOptions) || configOptionRouter($config) || DEFAULT_USE_ROUTER
}
```
shouldUseRouter() always return true because of `DEFAULT_USE_ROUTER`, so `SEGMENT_USE_ROUTER` config is useless.

### PR DESCRIPTION
**Pull request by fabiofdsantos**
Closes #42

### CODE REVIEW

File: lib/plugin.js [hunk 1]
```diff
@@ -1,22 +1,8 @@
...
-  return checkIfBoolean(moduleOptions.useRouter) ? moduleOptions.useRouter : undefined
-}
-
-function configOptionRouter($config) {
-  return checkIfBoolean($config.SEGMENT_USE_ROUTER) ? $config.SEGMENT_USE_ROUTER : undefined
-}
-
 function shouldUseRouter(moduleOptions, $config) {
-  return moduleOptionRouter(moduleOptions) || configOptionRouter($config) || DEFAULT_USE_ROUTER
+  return moduleOptions.useRouter || $config.SEGMENT_USE_ROUTER || true
```
Comment (rtouze) [inline lib/plugin.js]: OK, I see, `false || true` returns true, which is not what we want. Actually, what we want is:
`return moduleOptions.useRouter ?? $config.SEGMENT_USE_ROUTER ?? true`

Comment (fabiofdsantos) [reply lib/plugin.js]: @rtouze Yes, you're right. I was rushing into the issue :)
